version: '3'

services:
  gateway:
    build: gateway/
    ports:
    - 80:3000
    depends_on:
    - dog_grpc
    - cat_rest
    networks:
    - web
  dog_grpc:
    build: dog_grpc/
    ports:
    - 3000:3000
    networks:
    - web
  cat_rest:
    build: cat_rest/
    ports:
    - 3001:3000
    networks:
    - web

networks:
  web:
